/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package library.management.system;
import javax.swing.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
/**
 *
 * @author Auriga
 */
public class NewMember extends javax.swing.JFrame {

    /**
     * Creates new form NewMember
     */
    public NewMember() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        MemberIDF = new javax.swing.JTextField();
        NameF = new javax.swing.JTextField();
        AddressF = new javax.swing.JTextField();
        ContactF = new javax.swing.JTextField();
        EmailF = new javax.swing.JTextField();
        SaveBTN = new javax.swing.JButton();
        ClearBTN = new javax.swing.JButton();
        CloseBTN = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(300, 200));
        setMinimumSize(new java.awt.Dimension(750, 450));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(700, 450));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Member ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 66, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Address");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 154, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Contact");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 198, -1, -1));

        jLabel5.setFont(jLabel5.getFont().deriveFont(jLabel5.getFont().getStyle() | java.awt.Font.BOLD, jLabel5.getFont().getSize()+2));
        jLabel5.setText("Email");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 242, -1, -1));

        MemberIDF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        MemberIDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MemberIDFActionPerformed(evt);
            }
        });
        getContentPane().add(MemberIDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 63, 299, -1));

        NameF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(NameF, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 107, 299, -1));

        AddressF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddressF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddressFActionPerformed(evt);
            }
        });
        getContentPane().add(AddressF, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 151, 299, -1));

        ContactF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(ContactF, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 195, 299, -1));

        EmailF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(EmailF, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 239, 299, -1));

        SaveBTN.setText("Save");
        SaveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBTNActionPerformed(evt);
            }
        });
        getContentPane().add(SaveBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 299, -1, -1));

        ClearBTN.setText("Clear");
        ClearBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBTNActionPerformed(evt);
            }
        });
        getContentPane().add(ClearBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, -1, -1));

        CloseBTN.setText("Close");
        CloseBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseBTNActionPerformed(evt);
            }
        });
        getContentPane().add(CloseBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon("C:\\Users\\shaku\\Pictures\\Screenshots\\Screenshot 2024-11-18 092926.png")); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddressFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddressFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AddressFActionPerformed

    private void ClearBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBTNActionPerformed
        MemberIDF.setText("");
        NameF.setText("");
        AddressF.setText("");
        ContactF.setText("");
        EmailF.setText("");
    }//GEN-LAST:event_ClearBTNActionPerformed

    private void MemberIDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MemberIDFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MemberIDFActionPerformed

    private void SaveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBTNActionPerformed
        String MemberID = MemberIDF.getText();
        String Name = NameF.getText();
        String Address = AddressF.getText();
        String Contact = ContactF.getText();
        String Email = EmailF.getText();
        
        try 
            {
                Connection connection = Koneksi.konek();
                Statement st = connection.createStatement();
                st.executeUpdate("insert into members value('"+MemberID+"','"+Name+"','"+Address+"','"+Contact+"','"+Email+"')");
                JOptionPane.showMessageDialog(null,"Succes Update");
                setVisible(false);
                new NewMember().setVisible(true);
            }
            catch (Exception e)
            {
                JOptionPane.showMessageDialog(null,"MemberID already Exist");
                setVisible(false);
                new NewMember().setVisible(true);
            }
    }//GEN-LAST:event_SaveBTNActionPerformed

    private void CloseBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseBTNActionPerformed
        setVisible(false);
    }//GEN-LAST:event_CloseBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewMember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddressF;
    private javax.swing.JButton ClearBTN;
    private javax.swing.JButton CloseBTN;
    private javax.swing.JTextField ContactF;
    private javax.swing.JTextField EmailF;
    private javax.swing.JTextField MemberIDF;
    private javax.swing.JTextField NameF;
    private javax.swing.JButton SaveBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
